const cruces = [
["River Plate", "Racing de Córdoba"],
["Talleres", "Chacarita Juniors"],
["Club Atlético Colón", "Colegiales"],
["Lanús", "Sol de Mayo"],
["Club Atlético Gimnasia y Esgrima", "Excursionistas"],
["Unión", "Almagro"],
["Club Atlético Barracas Central", "Estudiantes (Caseros)"],
["Boca Juniors", "Olimpo"],
["Racing Club", "San Martín (Formosa)"],
["San Martín (Tucumán)", "Deportivo Morón"],
["Instituto", "Deportivo Riestra"],
["Huracán", "Yupanqui"],
["Independiente", "Club Ciudad de Bolívar"],
["Central Córdoba (Santiago del Estero)", "Comunicaciones"],
["Gimnasia y Esgrima de Mendoza", "All Boys"],
["Club Atlético Estudiantes", "Independiente (CH)"],
["Club Atlético Arsenal", "Villa Mitre"],
["Godoy Cruz", "Villa San Carlos/Defensores Unidos"],
["Sarmiento", "Chaco For Ever"],
["Rosario Central", "Central Norte"],
["Banfield", "Argentino (Merlo)"],
["Atlético Tucumán", "Estudiantes de Río Cuarto"],
["Club Atlético Defensa y Justicia", "Ituzaingó"],
["Tigre", "Centro Español/Defensores de Cambaceres"],
["San Lorenzo", "Sarmiento de Resistencia"],
["Platense", "Defensores de Belgrano"],
["Belgrano", "Independiente Rivadavia"],
["Newell's Old Boys", "Claypole"],
["Patronato", "Gimnasia y Tiro de Salta"],
["Argentinos Juniors", "Deportivo Armenio"],
["Club Atlético Aldosivi", "San Martín (San Juan)"],
["Vélez Sarsfield", "Deportivo Español"]
]
